### ISSUE TITLE
pre-trained models cannot be extracted

### ISSUE THREAD

**Issue by linaashaji** [bmartacho/UniPose#11]
Hello, 
I've downloaded the pre-trained models, but the tar files are broken and cannot be extracted.
Can we solve the problem please?

**Comment by bmartacho** [comment]
Weight files should not be extracted manually. The file will be open and loaded to the model in the following line of code:
https://github.com/bmartacho/UniPose/blob/ea0d368b8afe40f02c88e6423739a552d7628eed/unipose.py#L78
