### ISSUE TITLE
Number of classes in last_conv of decoder

### ISSUE THREAD

**Issue by HartleyTW** [bmartacho/UniPose#12]
Hi,

Thanks for this code, it's really useful.

I had a quick query about the last convolution in the decoder layer (labelled below). In the num_classes there is an addition of 5. What does this do? Removing it allows the LSP and MPII models to be loaded correctly, leaving it there gives the same error that issue #6 highlighted. 

```python
self.last_conv = nn.Sequential(nn.Conv2d(304, 256, kernel_size=3, stride=1, padding=1, bias=False),
                                       BatchNorm(256),
                                       nn.ReLU(),
                                       nn.Dropout(0.5),
                                       nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1, bias=False),
                                       BatchNorm(256),
                                       nn.ReLU(),
                                       nn.Dropout(0.1),
(THIS LINE ---->)                      nn.Conv2d(256, num_classes+1+5, kernel_size=1, stride=1))
```

**Comment by bmartacho** [comment]
Thank you for the feedback. The addition of 5 refers to the extraction of extra keypoints for the bounding box surrounding the person. 
For the case of simple keypoint estimation, please remove the addition of 5.
