### ISSUE TITLE
Error in loading state_dict for unipose

### ISSUE THREAD

**Issue by linaashaji** [bmartacho/UniPose#13]
Hello,
I'm trying to test the lstm_unipose model using the pretrained UniPose_LSTM_PennAction weights. I'm getting this error:

Error(s) in loading state_dict for unipose:
	size mismatch for backbone.conv1.weight: copying a param with shape torch.Size([64, 4, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 7, 7]).
	size mismatch for decoder.last_conv.8.weight: copying a param with shape torch.Size([14, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 256, 1, 1]).
	size mismatch for decoder.last_conv.8.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([19]).

**Comment by bmartacho** [comment]
Please refer to the following issue:
https://github.com/bmartacho/UniPose/issues/12#issuecomment-796672440

The differences in sizes correspond to different tests and applications of this work. Please select the appropriate in the following locations:
https://github.com/bmartacho/UniPose/blob/fe60478f8e88852c81d7d7c8860411ea987d2523/model/unipose.py#L34
https://github.com/bmartacho/UniPose/blob/fe60478f8e88852c81d7d7c8860411ea987d2523/model/modules/decoder.py#L31
