### ISSUE TITLE
Error in loading state_dict for unipos_LSTM

### ISSUE THREAD

**Issue by linaashaji** [bmartacho/UniPose#15]
Hello,
I'm trying to test the lstm_unipose model using the pretrained UniPose_LSTM_PennAction weights. I'm getting this error:

Error(s) in loading state_dict for unipose:
size mismatch for backbone.conv1.weight: copying a param with shape torch.Size([64, 4, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 7, 7]).

I don't know what is the origin of the fourth dimension in the model checkpoint. The Uni_pose LSTM 1st backbone Conv layer has 3 channels as input in the model.

**Comment by bmartacho** [comment]
During our experiments we tested a variety of configurations. A quick work around is to load your model with the following change on line 82 of UniposeLSTM.py prior to training your model.

`prefix = 'backbone.conv1'`

https://github.com/bmartacho/UniPose/blob/27234ff62c6e27f6d95a933c5ee2056e3e24e6ea/uniposeLSTM.py#L82

**Comment by YuQi9797** [comment]
Linaashaji, can you share the format of Penn_action_data dataset and the code, I don't know what the original author's corresponding dataset handling looks like?
