### ISSUE TITLE
How do you deal with invisible point of data during training?

### ISSUE THREAD

**Issue by YuQi9797** [bmartacho/UniPose#17]
Hello author, may I ask how you deal with the invisible points in the process of the experiment? The provided code also appears to perform a series of operations, such as heat map generation, on the invisible points.

**Comment by bmartacho** [comment]
"Invisible" or occluded keypoints are still tentatively estimated by the network with the location where the method believes there is a higher likelihood of it occurring.

For the testing on the datasets used in this paper, occluded joints are detected but not counted for accuracy, as per pre-defined metrics by the dataset challenges.

In case you would like to not have the occluded joints in your visualization, one possible approach would be to set a minimum confidence threshold for the detected joints. I.e. only show joints with detection confidence >= 0.5.
