### ISSUE TITLE
Local Maxima for Joints

### ISSUE THREAD

**Issue by YuQi9797** [bmartacho/UniPose#19]
Hello, Author.
      Where is the code of Local Maxima for joints? 
![image](https://user-images.githubusercontent.com/32479497/113976827-32bff000-9874-11eb-85d7-cf63a0275050.png)

is it there?  https://github.com/bmartacho/UniPose/blob/c9ae3789d9da6313e6aa45c884607cbda61fcfef/utils/utils.py#L92

And can you share me the meanning of this? the return maxvals is confidence of keypoints? what the preds is?
https://github.com/bmartacho/UniPose/blob/c9ae3789d9da6313e6aa45c884607cbda61fcfef/utils/evaluate.py#L63

**Comment by bmartacho** [comment]
The numpy functions `numpy.amax` and `numpy.argmax` return the location ID of the maximum response for the respective joints and its value (confidence), respectively.

https://github.com/bmartacho/UniPose/blob/c9ae3789d9da6313e6aa45c884607cbda61fcfef/utils/evaluate.py#L38

**Comment by YuQi9797** [comment]
Hello Sir,
https://github.com/bmartacho/UniPose/blob/c9ae3789d9da6313e6aa45c884607cbda61fcfef/utils/evaluate.py#L52
What the 'preds' it is?  If it is the final corresponding map for joint prediction, why are you directly using the heat map of the model output in the test, rather than the final map of the prediction(preds)?
https://github.com/bmartacho/UniPose/blob/c9ae3789d9da6313e6aa45c884607cbda61fcfef/unipose.py#L222
