### ISSUE TITLE
Person detection branch?

### ISSUE THREAD

**Issue by minhhoangbui** [bmartacho/UniPose#2]
Dear,
Thank you a lot for your work. And I have some questions to ask:
1) I don't see you train the person detection branch. How come you can predict bbox and pose at the same time as you claim?
2) In MPII, you use `segmented` folder. How can you find that annotation?
I'm looking forward to hearing from you

**Comment by minhhoangbui** [comment]
@bmartacho 
Thank you a lot for this answer. I'm a bit curious. Is it necessary to predict background heatmap. According to my understanding about top-down pose architecture, not many provide this.
Another thing, I think top-left point and bottom-right is enough to define a bounding box. Why you need 5 points in this case ?

**Comment by YHDang** [comment]
Hello，thanks for your discussion. I have a question about the evaluation of the Penn Action dataset. The paper said the evaluation follows [27], i.e. LSTM Pose Machines, so the torso is represented by the size of the bbox, right? But in the file `evaluate.py`, the torso was calculated by the  l2 norm of the difference between the neck and the pelvis. I'm a little confused about it. Could you give me some suggestions, please? @minhhoangbui @bmartacho Thanks very much!
