### ISSUE TITLE
The structure of wasp.

### ISSUE THREAD

**Issue by YuQi9797** [bmartacho/UniPose#20]
![image](https://user-images.githubusercontent.com/32479497/114498502-c7509680-9c56-11eb-9e77-98e213e59f7f.png)

Sir, I saw the picture the input is fed to AtrousModule where the dilation_rate = 6 firstly, but in your code the input is fed to AtrousModule  that dilation_rate = 24 firstly.

![image](https://user-images.githubusercontent.com/32479497/114498681-1dbdd500-9c57-11eb-931e-19d92eaee28f.png)

**Comment by YuQi9797** [comment]
What's the difference of this, in the module?

**Comment by bmartacho** [comment]
Please refer to the following regarding testing and experimentation of the dilation rates:

https://github.com/bmartacho/WASP/issues/1#issuecomment-563269567
