### ISSUE TITLE
Inference or demo is missing

### ISSUE THREAD

**Issue by simsim314** [bmartacho/UniPose#21]
Hi I understand it's a new work - and you published your pretrained model which is great. 

But as an end user who wants to check out your model quality for his purposes there is no simple code snippet to run inference, and no demo. It looks you have already written the test function and also have all the components for this. 

Yet no readme nor some basic indication how to infer the model on an image.

**Comment by bmartacho** [comment]
Thank you for the interest in UniPose. Please refer to the following issue addressing your question.

https://github.com/bmartacho/UniPose/issues/8#issuecomment-791405250

**Comment by A-qingtongxiaoyou** [comment]
Hi, I found the Inference by following #8 . But the Inference for a video still confuse me. 
[https://github.com/bmartacho/UniPose/blob/master/uniposeLSTM.py](url)
Line 223
```
    def test(self,epoch):
        self.model.eval()
        print("Testing") 
        
        img_path = '/PATH/TO/TEST/IMAGE'
```
It seems still the interface of a image. @bmartacho
