### ISSUE TITLE
the training set is LSPET ?  and test dataset is  LSP?

### ISSUE THREAD

**Issue by YuQi9797** [bmartacho/UniPose#23]
https://github.com/bmartacho/UniPose/blob/master/utils/utils.py#L234-L240

the training set is LSPET ?  and test dataset is  LSP?

**Comment by bmartacho** [comment]
The provided dataset by http://sam.johnson.io/research/lsp.html consists of LSPET for training and LSP for testing.

**Comment by jinchengll** [comment]
@YuQi9797 
你好，请问你已经成功运行作者的代码了吗？我没找到应该如何放置数据，比如MPII数据集和标签应该放置在哪里。

**Comment by yyunhh** [comment]
@bmartacho Hello, may I ask if the provided dataset link is closed right now?
-> http://sam.johnson.io/research/lsp.html (consists of LSPET for training and LSP for testing)
