### ISSUE TITLE
Model error while running unipose.py on Windows10

### ISSUE THREAD

**Issue by fxyQAQ** [bmartacho/UniPose#24]
The error I am getting is the following,
` from model.WASPpose.backbone import resnet`
`ModuleNotFoundError: No module named 'model.WASPpose'`
@bmartacho can you please let me know how I can run that successfully.
Thanks

**Comment by bmartacho** [comment]
I believe you are using an older version of the code. The directory for resnet.py is located at model.modules.backbone

https://github.com/bmartacho/UniPose/blob/9cb22c7237da20358282799139ca97b8f5295fde/model/modules/backbone/__init__.py#L1

**Comment by jinchengll** [comment]
@fxyQAQ 
Hello, have you run the code successfully? May I ask how the data is placed?
