### ISSUE TITLE
The performance when frequent parts occlusion occurrences

### ISSUE THREAD

**Issue by zhangrong1722** [bmartacho/UniPose#3]
Thank you for this great work. It is amazing that your framework does not require separate branches for bounding box and joint detections. As is said in your paper, the task of human pose estimation is challenging due to the frequent occurrence of parts occlusion. So I really want to know the performance of UniPose in such occasions. Is there same case or comparison with other methods in sequential video or single image?

Thank you.

**Comment by bmartacho** [comment]
Dear,
Thank you for the feedback and interest on UniPose. We do not have a specific numeric study of the occlusions. The paper only publish the overall accuracy. Although, the comparison was made by visual inspection during development and testing.
