### ISSUE TITLE
Where is waspnet defined? I'd like to use the pre-trained weights but am not able to define the model architecture

### ISSUE THREAD

**Issue by mukeshnarendran7** [bmartacho/UniPose#38]
NameError                                 Traceback (most recent call last)

[<ipython-input-31-a7874306a5e3>](https://localhost:8080/#) in <module>()
     58 
     59 if __name__ == "__main__":
---> 60     model = waspnet(backbone='resnet', output_stride=16)
     61     model.eval()
     62     input = torch.rand(1, 3, 513, 513)

NameError: name 'waspnet' is not defined

**Comment by A-qingtongxiaoyou** [comment]
Hi, i have the same bug as you. Could you tell me how to debug? Thanks!

**Comment by mukeshnarendran7** [comment]
Whats your mail id. I can share the notebook i used with you if you like. I was able to load the weights and all but you can test it further if you like

**Comment by A-qingtongxiaoyou** [comment]
***@***.***
Thank you very much for your reply！&nbsp;




彭畅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bmartacho/UniPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bmartacho/UniPose] Where is waspnet defined? I'd like to use the pre-trained weights but am not able to define the model architecture (Issue #38)





 
Whats your mail id. I can share the notebook i used with you if you like. I was able to load the weights and all but eventually I did not end up using it

**Comment by A-qingtongxiaoyou** [comment]
ctchang@mail.scut.edu.cn
Thank you very much for your reply！

**Comment by mukeshnarendran7** [comment]
Sent it.

**Comment by bring-nirachornkul** [comment]
I have this problem too. My e-mail is blinkdrive555@gmail.com

**Comment by IsraaSamkari** [comment]
Could you send me the whole code? I am facing many problems in fixing the code.
My e-mail is IsraaSamkari@hotmail.com
